### ISSUE TITLE
Support for tailing

### ISSUE THREAD

**Issue by evenh** [draperunner/cutters#1]
It would be super nice to have an option for tailing (`--tail` or `-wait`), e.g. seeing a wait time go up or down. This probably requires an option for filtering on a city/salon + polling to be useful.

**Comment by draperunner** [comment]
Looking for something like `watch 'npx cutters | grep Oslo'`, or am I misunderstanding? 

The `watch` program runs the following command every 2 sec. https://en.wikipedia.org/wiki/Watch_(Unix)

On Mac it's not included by default. Use `brew install watch` to install.

**Comment by evenh** [comment]
Sorry, I completely forgot about the existence of the `watch` utility – `watch -n 60 'npx cutters | grep Gunerius'` does the trick!
